# This default stack file is a copy of stack-ghc8.2.2.yaml
# But committing a symlink is probably a bad idea, so it's a real copy

resolver: lts-11.22 # ghc 8.2.2

extra-deps:
- cgi-3001.3.0.3
- httpd-shed-0.4.0.3
- exceptions-0.10.2
