name: Build Windows Package

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]
        ghc: ["8.6.5"]
        cabal: ["2.4"]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Haskell
      uses: actions/setup-haskell@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Install build tools
      run: |
        cabal install alex happy

    - name: Build GF
      run: |
        cabal install --only-dependencies
        cabal configure
        cabal build

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: macOS package
    #     path: dist/gf-*.pkg
    #     if-no-files-found: error
