name: Build macOS Package

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
        ghc: ["8.6.5"]
        cabal: ["2.4"]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Haskell
      uses: actions/setup-haskell@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Check cabal version
      run: |
        cabal --version

    - name: Install build tools
      run: |
        brew install \
          automake
        cabal v1-install alex happy

    - name: Build macOS package
      run: |
        make pkg

    - name: Copy packages
      run: |
        mkdir macos/dist
        cp ../gf_*.pkg macos/dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: macos/dist
