name: Build Debian Package

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    env:
      LC_ALL: C.UTF-8

    steps:
    - uses: actions/checkout@v2

    - name: Install build tools
      run: |
        sudo apt update
        sudo apt install -y \
          make \
          dpkg-dev \
          debhelper \
          haskell-platform \
          libghc-json-dev \
          python-dev \
          default-jdk \
          libtool-bin

    - name: Build Debian package
      run: |
        make deb

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Debian package
        path: ../gf_*.deb
        if-no-files-found: error
