name: Build Windows Binary

on:
  push:

jobs:
  windows:
    name: Build Windows package
    runs-on: windows-2019
    strategy:
      matrix:
        ghc: ["8.6.5"]
        cabal: ["2.4"]

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: >-
          base-devel
          gcc
          python-devel

    - name: Prepare dist folder
      shell: msys2 {0}
      run: |
        mkdir /c/tmp-dist
        mkdir /c/tmp-dist/c
        mkdir /c/tmp-dist/java
        mkdir /c/tmp-dist/python

    - name: Build C runtime
      shell: msys2 {0}
      run: |
        cd src/runtime/c
        autoreconf -i
        ./configure
        make
        make install
        cp /mingw64/bin/libpgf-0.dll /c/tmp-dist/c
        cp /mingw64/bin/libgu-0.dll /c/tmp-dist/c

    - name: Build Java bindings
      shell: msys2 {0}
      run: |
        export PATH="${PATH}:${JAVA_HOME_8_X64}/bin"
        cd src/runtime/java
        make \
          JNI_INCLUDES="-I \"${JAVA_HOME_8_X64}/include\" -I \"${JAVA_HOME_8_X64}/include/win32\" -I \"/mingw64/include\" -D__int64=int64_t" \
          WINDOWS_LDFLAGS="-L\"/mingw64/lib\" -no-undefined"
        make install
        cp .libs/msys-jpgf-0.dll /c/tmp-dist/java/jpgf.dll
        cp jpgf.jar /c/tmp-dist/java
        ls -al /c/tmp/dist/java

    - name: Build Python bindings
      shell: msys2 {0}
      env:
        EXTRA_INCLUDE_DIRS: /mingw64/include
        EXTRA_LIB_DIRS: /mingw64/lib
      run: |
        cd src/runtime/python
        python setup.py build
        python setup.py install
        cp /usr/lib/python3.8/site-packages/pgf* /c/tmp-dist/python

    - name: Setup Haskell
      uses: actions/setup-haskell@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Install Haskell build tools
      run: |
        cabal install alex happy

    - name: Build GF
      run: |
        cabal install --only-dependencies -fserver
        cabal configure -fserver
        cabal build
        copy dist\build\gf\gf.exe C:\tmp-dist

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: gf-${{ github.sha }}-windows
        path: C:\tmp-dist\*
        if-no-files-found: error
